### PR TITLE
add deploy

### PR DESCRIPTION
**Pull request by terrychenism**
deploy.prototxt added

### CODE REVIEW

**Comment by forresti** [comment]
Thanks for your contribution! We will run some tests and let you know if anything needs to be changed. :)

**Comment by forresti** [comment]
Couple of notes:

1. We use the default values of `lr_mult` and `decay_mult` during training, so there's no need to include them in the prototxt
2. If I'm not mistaken, `bias_filler`, `lr_mult`, etc are all used for weight initialization at the beginning of training, but they have no affect on inference. So, we can probably remove all of these things from deploy.prototxt if we want to keep it simple.

**Comment by terrychenism** [comment]
Good suggestions, I have updated the deploy file

**Comment by forresti** [comment]
Merged as https://github.com/DeepScale/SqueezeNet/commit/445b1d97f8cfd106727e658d17222b24cfddf17d

**Pull request closed without merging**
